### ISSUE TITLE
Question about branch export_cmake

### ISSUE THREAD

**Issue by dch4o** [berndpfrommer/basalt-headers#1]
Hi,
Thank you for sharing your work, even in header-only version of Basalt.

I have question about the branch 'export_cmake'. 

Is this branch is under development? 
The most recent commit is pushed into this branch but the library installation fails on my machine with:
```bash
$ mkdir build && cd build
$ cmake ..
...
CMake Error: install(EXPORT "basalt-headersTargets" ...) includes target "basalt-headers" which requires target "sophus" that is not in any export set.
CMake Error: install(EXPORT "basalt-headersTargets" ...) includes target "basalt-headers" which requires target "cereal" that is not in any export set.
```

As described in the error messages, I found out that installing targets from `cereal` and `sophus` fails when they imported as a submodule.
There was no problem when I tried with the cmake options `-DBASALT_BUILTIN_SOPHUS=OFF` and `-DBASALT_BUILTIN_CEREAL=OFF` after manually installed those libraries.

So, my guess is that there should be some problem linking Sophus and Cereal to **interface** library basalt-headers.
Any ideas?

**Comment by dch4o** [comment]
FYI:
My environment as follows
- Ubuntu 20.04 LTS
- cmake 3.16.3

**Comment by berndpfrommer** [comment]
This branch is used for the [basalt_wrapper](https://github.com/berndpfrommer/basalt_wrapper) repository. I never use it directly with bare cmake, just within ROS's ament build system.
You can try reinstating the EXCLUDE_ALL for sophus and cereal that I removed.

**Comment by dch4o** [comment]
Thank you for your comment.
Wish the direct cmake version could be released someday!
